Save/load adaptive templates scripts from Motor-CAD api
ansys/pymotorcad pull request #201
Opened 2023-10-04 14:42 UTC by matthewAnsys

2023-10-06 15:59 UTC, jgsdavies requested changes

2023-10-06 15:59 UTC, jgsdavies commented on tests/test_geometry.py
> +def test_load_adaptive_script():
Can we run the script in motorcad and check for changed params

2023-10-06 16:32 UTC, jgsdavies commented on tests/test_geometry.py
> +def test_load_adaptive_script():
Also if you are modifying the script can you save it in temp files so that the tracked file isn't changed

2023-10-09 07:05 UTC, matthewAnsys commented on tests/test_geometry.py
> +def test_load_adaptive_script():
The file is now saved to temp folder.

2023-10-09 09:45 UTC, jgsdavies approved these changes

2023-10-09 09:46 UTC, merged