Docs update for 24r1
ansys/pymotorcad pull request #224
Opened 2023-11-14 09:50 UTC by jgsdavies

2023-11-14 12:02 UTC, matthewAnsys requested changes

2023-11-14 12:02 UTC, matthewAnsys commented on doc/source/user_guide/Motor-CAD_setup.rst
> +By default, if Motor-CAD is launched by an external script, the GUI is not shown. This improves the speed of startup
```suggestion
If Motor-CAD is launched by an external script then by default the GUI is not shown. This improves the speed of startup
```

2023-12-04 12:34 UTC, JackB-Ansys submitted a review, later dismissed

2023-12-07 10:35 UTC, matthewAnsys approved these changes

2024-01-09 12:29 UTC, jgsdavies commented
Only CodeCov is failing - I moved some functions that were untested. Happy to submit anyway

2024-01-11 16:26 UTC, JackB-Ansys approved these changes

2024-01-25 10:59 UTC, merged