Feat/get region dxf api
ansys/pymotorcad pull request #299
Opened 2024-04-29 12:51 UTC by matthewAnsys

Add api for accessing dxf regions from Motor-CAD

2024-04-29 15:12 UTC, PipKat commented on src/ansys/motorcad/core/methods/adaptive_geometry.py
> +            name of region.
```suggestion
            Name of the region.
```

2024-04-30 09:17 UTC, jgsdavies commented on src/ansys/motorcad/core/methods/adaptive_geometry.py
> +        self.connection.ensure_version_at_least("2024.0")
2024

2024-04-30 09:18 UTC, jgsdavies requested changes

2024-04-30 09:18 UTC, jgsdavies commented on src/ansys/motorcad/core/methods/adaptive_geometry.py
> +        self.connection.ensure_version_at_least("2024.0")
```suggestion
        self.connection.ensure_version_at_least("2024.2.0")
```

2024-04-30 09:18 UTC, jgsdavies commented on tests/test_geometry.py
> +    mc.load_dxf_file(get_dir_path() + r"\test_files\dxf_import.dxf")
I think this file needs to be added to PR

2024-05-14 13:16 UTC, jgsdavies commented on src/ansys/motorcad/core/methods/adaptive_geometry.py
> +        self.connection.ensure_version_at_least("2024.0")
```suggestion
        self.connection.ensure_version_at_least("2024.2")
```

2024-05-14 13:17 UTC, jgsdavies approved these changes

2024-05-14 13:17 UTC, merged