Workaround-twinbuilder-thermal-new-heat-flow-method
ansys/pymotorcad pull request #405
Opened 2024-10-16 18:30 UTC by HusainAdam

2024-10-17 15:26 UTC, jgsdavies requested changes

2024-10-17 15:26 UTC, jgsdavies commented on examples/links/thermal_twinbuilder.py
> +                    "Warning - The Improved Fluid Heat Flow Method setting in this .mot file is "
warnings.warn instead

2024-10-17 16:22 UTC, HusainAdam commented on examples/links/thermal_twinbuilder.py
> +                    "Warning - The Improved Fluid Heat Flow Method setting in this .mot file is "
Corrected

2024-10-21 14:19 UTC, HusainAdam commented on examples/links/thermal_twinbuilder.py
> +                if node not in graphNodes:
Fix for spray cooling systems with lone single nodes

2024-10-21 15:38 UTC, jgsdavies approved these changes

2024-10-22 08:09 UTC, merged